version: 2

sources:
  - name: raw
    database: dbt_db
    schema: analytics
    tables:
      - name: raw_customers
        description: "Raw customer data uploaded from CSV"
        columns:
          - name: customer_id
            description: "Unique identifier for each customer"
            tests:
              - not_null
              - unique
          - name: name
            description: "Customer name"
          - name: signup_date
            description: "Date the customer signed up"

      - name: raw_orders
        description: "Raw order data uploaded from CSV"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Foreign key to raw_customers"
          - name: order_date
            description: "Order date"
          - name: amount
            description: "Order amount in USD"

      - name: raw_events
        description: "User events like pageviews, clicks, etc."
        columns:
          - name: event_id
            description: "Unique identifier for each event"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Foreign key to raw_customers"
          - name: event_type
            description: "Type of event (e.g., click, purchase)"
          - name: event_time
            description: "Timestamp of the event"
